<template>
  <HeadBackground />
  <Title class='horizontal-center' :title='$t("MSG_AGREEMENT_TO_TERMS")' :subtitle='$t("MSG_LAST_UPDATED", { DATE: new Date("2023-07-08").toDateString() })' />
  <div class='content-width row horizontal-center'>
    <div class='left' :style='{marginTop: tableOfContentMarginTop}'>
      <TableOfContent v-model:selected='selected' :entries='entries' />
    </div>
    <div class='right text-primary'>
      <q-scroll-observer @scroll='onScroll' />
      <q-resize-observer @resize='(size) => onResize(size)' />
      <div class='text-primary title title-1' :style='{marginBottom: "24px"}'>
        Special notes:
      </div>
      <p>Welcome to the CRYPTO MORE!</p>
      <h5 class='text-primary title title-2'>
        Agreement last updated date: Sat Jul 08 2023
      </h5>
      <p>These terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you" or "User") and, CRYPTO MORE LTD. ("Crypto More", "we", "us", or "our"), concerning your access to and use of the https://cryptomore.io/ website (the "Site") as well as any other media form, media channel, mobile website digital service, Validator Services, Subscription Services or mobile application related, linked, or otherwise connected thereto or provided by us (collectively, the "Services").You agree that by accessing the Site or using any of the Services, you have read, understood, and agreed to be bound by all of these terms, In particular, in bold form to prompt your attention to the terms.</p>
      <p>You have the right to agree or disagree with this agreement. You will be deemed to have read and accepted all the terms of this agreement by clicking the "By continuing, I understand and agree" button, and agree that we collect, use, disclose and process the information described in our privacy policy.</p>
      <p>If you do not agree with any or all of these terms, then you are expressly prohibited from using this site and service and you must discontinue use immediately.</p>
      <p>The information provided on the Site and our Services are not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. <span class='text-primary' :style='{fontWeight:600}'>Accordingly, those persons who choose to access the Site or Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</span> Our Services are intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use our Services or our Site.</p>
      <p>This "Special notes" is an integral part of the text of this agreement.</p>
      <h4 class='text-primary title title-1' id='User Account'>
        User Account
      </h4>
      <p><span class='text-primary title title-2'>Capacity.</span> You confirm, that you should be the legal person, corporation or other organization with full capacity of conduct and civil rights while finishing the registering process or actually use the Term by the methods we are allowable. If not, you or your guardian should undertake all consequences. We have the right to log off or permanently suspend your account and ask for compensation.</p>
      <p><span class='text-primary title title-2'>Pre-registration commitments.</span> By registering an account, you commit to and guarantee that you are a person who can legally access our services in accordance with the laws of your jurisdiction.</p>
      <p><span class='text-primary title title-2'>Account registration.</span> When registering a user account, you should provide real and valid information (including email address, or mobile phone number); after registering or activating, you should comply with the laws and regulations and the provisions of this agreement, according to the page prompt timely and correct to provide and update your information, make it true, timely, complete and accurate. If we have reasonable grounds to suspect that the information you provide is incorrect, untrue, out of date or incomplete, we have the right to send you a letter of inquiry or request you to amend or delete the relevant information directly, or even suspend or stop providing some or all of the services. We accept no responsibility for any direct or indirect losses or adverse consequences that you may suffer.</p>
      <p>You are deemed to be bound by this clause if you complete the information or read and agree to all steps of registration after you have checked the registration page notice, or if you use this clause in any other way that we allow. You can use an e-mail address or phone number as a way to log in to Crypto More. <span class='text-primary' :style='{fontWeight:600}'>If you provide incorrect information during registration, we will not accept any responsibility. If you therefore suffer any direct or indirect losses and adverse consequences, you are not entitled to claim against us.</span></p>
      <p>You should fill in and update the e-mail address or cell phone number information you provided so that we can contact you effectively. <span class='text-primary' :style='{fontWeight:600}'>If we are unable to contact you through these means, resulting in any loss or increase in your expenses, you should bear full responsibility.</span> You have been informed and agreed that you must ensure that the contact information you provide is valid and that you follow our instructions for modifications or updates.</p>
      <p>Your account is yours to set up and keep, we will not ask you to provide your account password at any time. <span class='text-primary' :style='{fontWeight:600}'>So you are responsible for the confidentiality of your username and password, and keep confidential all activities that take place under your username and password, including but not limited to disclosure and publishing, online click-to-agree or submit rules and agreements, online agreement renewal or purchase services, account setup, etc.. You agree:</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Any successful login to and use of our website/application or service through your account and password shall be deemed to be your own act of use and you shall be liable for all the activities and consequences of your account.</span></p>
      <p>If you lose your password, you can retrieve it using the official method by Crypto More.</p>
      <p>Without our consent, you cannot buy, sell, transfer, lease your account on the website and related services. We shall not be liable for any losses or consequences arising from your voluntary disclosure, lending of account information, or from any other person's attack, fraud, etc., you can recover from the tortfeasor through judicial and administrative remedies.</p>
      <p>Ensure that you will strictly adhere to the web/services' security, authentication, configuration, and operation strategies or procedure.</p>
      <p>Ensure that you leave our website/services in the right steps for finishing every online period. <span class='text-primary' :style='{fontWeight:600}'>We cannot and will not be responsible for any of your losses due to your violating the Term. You will comprehend that it needs reasonable time for us to take action according to your requirement. We will not undertake any responsibilities for the consequences (including but not limited to any of your losses) that occurred before we take action.</span></p>
      <p>You should notify us immediately if you notice any unusual activity in your account, including, but not limited to, password tampering, unauthorized login or use by others. If your account is used by others due to your failure to maintain the confidentiality of your account information, thereby causing us or other visitors to the site to suffer losses, you may be liable for the losses.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>You may not use another person's account at any time without the explicit permission of the account holder. We shall not be liable for any loss to you or others arising from your failure to comply with this section.</span></p>
      <h4 class='text-primary title title-1' id='Description of Our Services'>
        Description of Our Services
      </h4>
      <p>Crypto More is a start-up company whose vision is to provide crypto platform, infrastructure and service to application developer, crypto business organization and crypto investors. Our goal is to make developing, staking and starting new crypto business easier for developers, organizations and individuals. Crypto More's business model includes several components such as monetizing idle resources from world-class data centers and providing blockchain node hosting solutions, providing crypto subscription to developers, deploying one-stop crypto business infrastructure for organization, etc. Crypto More will provide developers with the ability to subscribe different crypto APIs such as blockchain node indexer, multi-tenancy crypto application service, etc. Crypto More will also provide private deployment solution to organizations who have more strict policy of their data and infrastructure. We focus on providing easy-to-use platform and service to our users. We provide service as agreed Service Level Agreement with You, as our individual client, with higher resilience and minimized latency.</p>
      <h4 class='text-primary title title-1' id='Updates, Amendments, Changes to Terms'>
        Updates, Amendments, Changes to Terms
      </h4>
      <p>Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. <span class='text-primary' :style='{fontWeight:600}'>We reserve the right, in our sole discretion, to make changes or modifications to these terms at any time and for any reason. We will alert you about any changes by updating the "Last Updated" date of these terms, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these terms to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised terms by your continued use of the Site after the date such revised terms are posted.</span></p>
      <h4 class='text-primary title title-1' id='Fees and Payment'>
        Fees and Payment
      </h4>
      <p>Some Services, including paid Services up to a certain use threshold, may be offered to the public and licensed on a royalty-free basis.</p>
      <p>The relevant fees we charge you will be prompted on the page, other than that you do not charge any fees. If you do not accept our products/services, please do not pay the fees and stop using this website immediately. If you continue to use this website, you will be deemed to accept the relevant fees and charges, you should pay us according to the charge prompt. If you complete the payment, you are deemed to have successfully purchased our products/services on a voluntary basis. We reserve the right to charge, including the function of setting charges, determine the charge object, charge period or charge rate, etc.</p>
      <p>Unless otherwise specified in an order form for Services, to the extent a Service incurs fees, we calculate and bill fees and charges monthly according to your Plan or as otherwise advertised and charged on the Service If you make any other changes to the Services during a billing period (e.g., upgrading or downgrading your Selected Plan), we will apply any additional charges or credits to the next billing period. We may bill you more frequently for Fees accrued if we suspect that your account is fraudulent or at risk of non-payment.</p>
      <p>You agree to keep a cryptocurrency wallet on file with Crypto More.<span class='text-primary' :style='{fontWeight:600}'> If your payment card expires or its cryptocurrency wallet is depleted, you must notify Crypto More immediately.</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>In accordance with the requirements of the applicable law, each party shall be responsible for the identification and payment of all taxes and other government fees and charges (and any penalties, interest and other surcharges) imposed on it as a result of transactions and payments made under this agreement. Unless otherwise stated, all expenses you should pay are not included in tax. We reserve the right to withhold tax when necessary.</span></p>
      <p>You can close your account at any time. However, you are still obligated to fulfill your responsibilities for any pending transaction. In addition, you will be responsible to us for any costs incurred prior to the closure.</p>
      <p>Crypto More may suspend your access to the Platform if we are unable to process any payment due to an expired or invalid payment card or a depleted cryptocurrency wallet. Crypto More will use commercially reasonable efforts to notify you and provide you an opportunity to provide updated payment information prior to suspending access. If applicable to a particular Service, we retain sole discretion to limit your usage of the Services (including without limitation by limiting the number of API requests you may submit ("API Requests")) at any time if your usage of the Services exceeds the applicable Threshold for your Selected Plan of Service.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Furthermore, we may suspend Your right to access or use any portion or all of the Services immediately upon notice to you if we determine:</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>(a) your use of the Services (i) poses a security risk to the Services or any third party, (ii) could adversely impact our systems, the Services, or the systems of any other user, (iii) could subject us, our affiliates, or any third party to liability, or (iv) could be fraudulent;</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>(b) you are in breach of this Agreement.</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>We may change or discontinue any or all of the Services or change or remove functionality of any or all of the Services from time to time. We will notify you of any material change to or discontinuation of the Services. For any discontinuation of or material change to a Service, we will use commercially reasonable efforts to continue supporting the previous version of the Service for a period of time after the change or discontinuation (except if doing so (a) would pose a security or intellectual property issue, (b) is economically or technically burdensome, or (c) would cause us to violate the law or requests of governmental entities).</span></p>
      <p>Customer is responsible for all activity occurring under Customer's accounts, and for complying with all laws and regulations applicable to Customer's use of the Service. <span class='text-primary' :style='{fontWeight:600}'>Customer also must (a) notify Crypto More promptly upon becoming aware of any unauthorized use of any Customer password or account (or any other breach of security of the Service), and (b) notify Crypto More promptly upon becoming aware of, and make a reasonable effort to stop, any unauthorized copying, distribution or misuse of any aspect of the Service. We are entitled to claim damages from you if Crypto More's losses are increased as a result of your inaction or failure to make reasonable efforts in the circumstances described above.</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>If you choose to negotiate with Crypto More to customize the specific service content and payment amount, you know that all the content in the communication and negotiation process does not constitute any promise and guarantee of Crypto More, the service content, service method and payment amount are subject to the final version service agreement with you.</span></p>
      <h4 class='text-primary title title-1' id='Privacy'>
        Privacy
      </h4>
      <p>We collect information that you provide to us, the information we obtain automatically when you use our Services, and the information from other sources such as third-party services and organizations, as described below. You confirm and agree that we have the right to collect your information by:</p>
      <ul>
        <li>
          <span class='text-primary' :style='{fontWeight:600}'>Create an account.</span> We may collect personal information that you provide to us, including your e-mail address and cell phone number.
        </li>
        <li>
          <span class='text-primary' :style='{fontWeight:600}'>Purchases.</span> We may collect personal information and details associated with your purchases, including payment information. Any payments made via our Services are processed by third-party payment processors. We do not directly collect or store any payment information entered through our service, but we may receive information related to your payment.
        </li>
        <li>
          <span class='text-primary' :style='{fontWeight:600}'>Feedback and correspondence.</span> You may provide your information in your responses to surveys when you report a problem with Service, receive customer support, or otherwise correspond with us.
        </li>
      </ul>
      <p>Information Automatically Collected. We may automatically record certain information about how you use Crypto More (we refer to this information as "Log Data"). Log Data may include information such as a user's Internet Protocol (IP) address, device and browser type, operating system, the pages or features of Crypto More to which a user browsed and the time spent on those pages or features, the frequency with which the Sites are used by a user, search terms, the links on Crypto More that a user clicked on or used, and other statistics. We use this information to administer the Service and we analyze (and may engage third parties to analyze) this information to improve and enhance the Service by expanding its features and functionality and tailoring it to our users' needs and preferences.</p>
      <p>We may use cookies, local storage, or similar technologies to analyze trends, administer the Sites, track users' movements around the Sites, and gather demographic information about our user base as a whole. Users can control the use of cookies and local storage at the individual browser level. For more information, please see our Cookies Policy.</p>
      <p>We also may use Google Analytics to help us offer you an optimized user experience. You can find more information about Google Analytics' use of your personal data here: https://www.google.com/analytics/terms/us.html. Please note that Metamask does not use Google Analytics in its wallet.</p>
      <p>Third-Party Services and Sources. We may obtain personal information about you from other sources, including through third-party services and organizations. For example, if you access our Services through a third-party application, such as an app store, a third-party login service, or a social networking site, we may collect personal information about you from that third-party application that you have made available via your privacy settings.</p>
      <p>You are aware that after deleting or canceling your information, we have the right to the relevant laws and regulations and network security considerations, continue to save but do not use your user information and other data.</p>
      <p>We would never collect information. We will never ask you to share your private key or wallet seed. Never Trust anyone or any website that asks you to enter your private key or wallet seed.</p>
      <h4 class='text-primary title title-1' id='Term and Termination'>
        Term and Termination
      </h4>
      <p>These terms shall remain in full force and effect while you use the Site or Services.</p>
      <p>If you have seriously violated these terms and have not rectified them within 30 days from the date of receipt of our notice, we may unilaterally terminate these terms: (1) you are in breach of this agreement, we terminate this agreement in accordance with the terms of breach of contract; (2) you misappropriate other people's accounts, defraud other people's property, disturb the market order, take improper means for profit, etc. , we according to the rules of the website to your account to be closed; (3) in addition to the above circumstances, because you repeatedly violated the rules of the website related regulations and serious, we according to the rules of the website to your account to be closed; (4) your account has been recovered by us; (5) in accordance with the legal provisions or the requirements of the competent authorities; (6) users of negative news may affect our goodwill and our company; (7) for security reasons or other necessary circumstances; (8) other circumstances in which service shall be terminated.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Upon termination or rescission of this agreement, you will be informed that: (1) from the date of termination or rescission of this agreement, we will close your account permissions on the site. (2) it is the user's responsibility to back up the data and information stored in Crypto More. (3) upon termination or rescission of this agreement, you agree that we have the right to retain your registration information, transaction records and other data, but we do not undertake to provide you or any third party with any data and information after termination of this agreement, nor shall I be liable to you or any third party for the termination of this agreement, unless otherwise provided by law or regulation. (4) after the termination or rescission of this agreement, we reserve the right to hold you responsible for your past illegal and breach of contract.</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Loss resulting from the suspension or termination of our web services to you pursuant to this agreement, resulting in your inability to continue to use the web services, or the inability or incomplete performance of the services purchased, we take no responsibility.</span></p>
      <p>If we terminate or suspend your access to our Site or Services for any reason, you are prohibited from registering or accessing them in any other manner. In addition to terminating or suspending your access to our Services and Site, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
      <h4 class='text-primary title title-1' id='Intellectual Property'>
        Intellectual Property
      </h4>
      <p>Crypto More Inc. is the owner and intellectual property owner of this website and related services.</p>
      <p>The above-mentioned websites and related services refer to the creativity, design, structure, presentation, graphics, graphics, visual interface and computer coding, artwork, photos, portraits, button icons and computer software, logos, digital downloads, data compilation, etc. which are provided by us, including but not limited to all text, pictures, audio, video, animation, trademarks, service logos, trade names, patterns, graphics, visual interfaces and computer coding, as well as computer software, logos, digital downloads, data compilation, etc. , are owned, controlled or legally authorized by us. You may not use the contents of this website for any commercial purpose without our prior written consent, unless this agreement expressly provides.</p>
      <p>The technology and content used to offer, or provided in connection with, our Platform and Website, including the software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof, are exclusively owned by Crypto More Inc., its licensors or other providers of such material and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
      <p>You agree that we have the right to use your intellectual property rights without additional authorization for the information you publish and disclose on our platform and website. Without our written permission, you shall not, by yourself or by authorization, assist any third party to collect intellectual property-related content of this website or platform in a regular or unconventional manner.</p>
      <p>In the course of using our website and services, you may use third party functions or services, and you shall comply with the relevant provisions of the third party in addition to the relevant provisions of this agreement, and respect the relevant rights of third parties.</p>
      <h4 class='text-primary title title-1' id='Representations and Warranties'>
        Representations and Warranties
      </h4>
      <p>Crypto More makes no warranty that: (1) The Website or content will meet the Customer's requirements; (2) The Website will be available on an uninterrupted, timely, secure, or error-free basis; (3) The results that may be obtained from the use of the Website or any content provided on or through the Website will be accurate or reliable; or (4) the quality of any content purchased or obtained by Customer on or through the Website will meet Customer's expectations.</p>
      <p>Additionally, Customer represents and warrants to Crypto More that (a) Customer has obtained and shall obtain all necessary rights and consents to provide Crypto More with the Customer Data including, with respect to any personal information contained therein, the express consent from any applicable individuals to disclose and transfer such information to Crypto More for the purposes contemplated herein, and (b) that the Customer Data and the Nodes do not and shall not infringe, misappropriate, or otherwise violate the rights of any third party including, without limitation, intellectual property rights.</p>
      <p>You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Services ("Submissions") provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you. You hereby waive all moral rights to any such Submissions, and you hereby warrant that any such Submissions are original with you or that you have the right to submit such Submissions. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions.</p>
      <p>You agree to receive information from Crypto More, including but not limited to marketing campaigns, product deals, promotions, etc.</p>
      <p>All your actions while using Crypto More should follow the rules of the website published by Crypto More in real time; if you need to open, apply for, or use a different service that we publish or qualify for that service, you should complete the qualification certification and application according to the specific rules and procedures published by Crypto More, provide the necessary information and ensure the authenticity and accuracy of the information; You should enter into agreements (if necessary) with us or the parties providing the specific services, and strictly abide by such agreements; the specific content of your use of such services shall be subject to the relevant agreements and website rules.</p>
      <p>You should avoid getting Crypto More involved in political and public events by using Crypto More, or we have the right to suspend or terminate use of your site.</p>
      <p>Users are prohibited from using Crypto More in any form as a venue, website or medium for all kinds of illegal activities. Without our authorization or permission, users are not allowed to use Crypto More for any business purpose or in any form as a place, website or medium for any business purpose.</p>
      <p>You are fully aware and understand that due to the unique nature of online transaction services, we are not obligated to review all users' use of my Crypto More in advance and in real time. But in one of the following cases, we can judge independently by the standard of knowledge level of ordinary, non-professional people or by the information we have, we have the right to take actions including, but not limited to, restricting users' access, requesting users to provide relevant information, issuing warning notices, deleting relevant information, suspending or terminating users' use of our website or service, publicizing users' violation of laws or contracts by means of internet announcement, or dealing with other violations of the contract by users in accordance with the website rules: (1) users violating state laws, regulations, regulations and regulatory documents; (2) the user violates this agreement or any website rule; (3) the third party notifies us that the user violates the third party's lawful rights and interests.</p>
      <p>You understand and agree that we will do our best to ensure the consistency and security of the use of the site at the current level of technology and conditions, but we cannot always anticipate and guard against legal, technical and other risks, including, but not limited to, force majeure, large-scale virus, Trojan Horse and hacker attacks, system instability, third-party service flaws, government regulation and other reasons may lead to the use of the site interruption, data loss and other losses and risks.</p>
      <p>To the extent permitted by law, we are not liable for service disruption or obstruction caused by (1) a computer virus, Trojan, or other malicious program or hacker attack; (2) a failure of the user or our computer software, systems, hardware and communication lines; (3) improper user operation; (4) the user uses the website in a manner not authorized by US; (5) other circumstances beyond our control or reasonable expectation.</p>
      <p>We reserve the right to modify or interrupt the service at any time without notice to the user. We exercise the right to modify or interrupt the service without being responsible to the user or any other third party.</p>
      <p>No responsibility for typographical errors, omissions, etc. on the site that are not caused by us on purpose. We have the right but no obligation to improve or correct any omission or error in any part of this website.</p>
      <p>Unless we expressly agree in writing that any information that users may obtain from this website by any means, including but not limited to including, through, connecting to or downloading from this website, including, but not limited to, advertisements, etc., without warranting their accuracy, completeness or reliability; for any products, services, information or materials purchased or obtained by users as a result of the content information on this website, we take no responsibility. The user shall bear the risks arising from the use of the information content on this website.</p>
      <p>This website and its contents are for your convenience only. We do not give any form of warranty as to the availability, continuity or accessibility of this website and its contents and services. This website and its contents are provided on a "Status quo" basis. You are fully responsible for the use of this site and any linked sites. If you are not satisfied with all or part of the site, your only remedy is to stop using all or part of the site. The remedy limit is part of your agreement with us.</p>
      <h4 class='text-primary title title-1' id='Disclaimer'>
        Disclaimer
      </h4>
      <p>The site and services are provided on an as-is and as-available basis. You agree that your use of the site and our services will be at your sole risk. to the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the services and your use thereof, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We make no warranties or representations about the accuracy or completeness of the site's content or the content of any websites linked to the site and we will assume no liability or responsibility for any (1) errors, mistakes, or inaccuracies of content and materials, (2) personal injury or property damage, of any nature whatsoever, resulting from your access to and use of the site or services, (3) any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, (4) any interruption or cessation of transmission to or from the site or services, (5) any bugs, viruses, trojan horses, or the like which may be transmitted to or through the site or to you by any third party, and/or (6) any errors or omissions in any content and materials or for any loss or damage of any kind incurred as a result of the use of any content posted, transmitted, or otherwise made available via the site. (7) any damage caused to you by force majeure or for reasons beyond our control (8) unless otherwise agreed, if the period of use or the indicated period of use is "Permanent" or similar expression, the period of use is for you to start using the service until the date when the service is offline on this website or platform. We do not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the site, any hyperlinked website, or any website or mobile application featured in any banner or other advertising, and we will not be a party to or in any way be responsible for monitoring any transaction between you and any third-party providers of products or services. As with the purchase of a product or service through any medium or in any environment, you should use your best judgment and exercise caution where appropriate.</p>
      <p>In no event will we or our directors, employees, or agents be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, or other damages arising from your use of the site or services, even if we have been advised of the possibility of such damages. Not with standing anything to the contrary contained herein, our liability to you for any cause whatsoever and regardless of the form of the action, will at all times be limited to the amount paid, if any, including a share of our fees collected from you proportionate to the amounts you stake or delegate through us, by you to us during the three months period prior to any cause of action arising. Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers or limitations may not apply to you, and you may have additional rights.</p>
      <h4 class='text-primary title title-1' id='Indemnification'>
        Indemnification
      </h4>
      <p><span class='text-primary' :style='{fontWeight:600}'>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of (1) use of the Site or Services; (2) breach of these terms; (3) any breach of your representations and warranties set forth in these terms; (4) your violation of the rights of a third party, including but not limited to intellectual property rights; or (5) any overt harmful act toward any other user of the Site or Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</span></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>If the third-party claims for the above reasons cannot cover our losses, we are entitled to claim on You for your part of the fault.</span></p>
      <h4 class='text-primary title title-1' id='Force Majeure'>
        Force Majeure
      </h4>
      <p>Users understand and agree that they may encounter risk factors such as force majeure interruptions in the use of our website or services. An Force Majeure is an objective event that cannot be foreseen, overcome, or avoided and that has a significant impact on one or both parties, including but not limited to natural disasters such as floods, earthquakes, epidemics and storms, as well as social events such as war, unrest, government behavior. In the case of the above, we will try to cooperate with the relevant units in the first time to repair in a timely manner, but the resulting losses to users, we will be exempted from liability within the scope of the law.</p>
      <h4 class='text-primary title title-1' id='Binding Arbitration and Class Action Waiver'>
        Binding Arbitration and Class Action Waiver
      </h4>
      <p>Please read this section carefully-it may significantly affect your legal rights, including your right to file a lawsuit in court.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Binding Arbitration. Any dispute, claim or controversy ("Claim") relating in any way to this Agreement, the Site, or your use of the Offerings will be resolved by binding arbitration as provided in this Section,</span> rather than in court, except that you may assert claims in small claims court if your claims qualify.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>If you are located in the United States:</span> This agreement and any dispute or claim (including non-contractual disputes or claims) arising out of or in connection with it or its subject matter or formation shall be governed by and construed in accordance with the laws of the State of Texas. The Federal Arbitration Act and federal arbitration law apply to this Agreement. There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages), and must follow the terms of this Agreement as a court would. The arbitration will be conducted in accordance with the expedited procedures set forth in the JAMS Comprehensive Arbitration Rules and Procedures (the "Rules") as those Rules exist on the effective date of this Agreement, including Rules 16.1 and 16.2 of those Rules. The arbitrator's decision shall be final, binding, and non-appealable. Judgment upon the award may be entered and enforced in any court having jurisdiction. Neither party shall sue the other party other than as provided herein or for enforcement of this clause or of the arbitrator's award; any such suit may be brought only in a Federal District Court or a Texas state court located in Tarrant County, Texas. The arbitrator, and not any federal, state, or local court, shall have exclusive authority to resolve any dispute relating to the interpretation, applicability, unconscionability, arbitrability, enforceability, or formation of this Agreement including any claim that all or any part of the Agreement is void or voidable. If for any reason a claim proceeds in court rather than in arbitration we and you waive any right to a jury trial. Notwithstanding the foregoing we and you both agree that you or we may bring suit in court to enjoin infringement or other misuse of intellectual property rights.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>If you are located in the United Kingdom:</span>This agreement and any dispute or claim (including non-contractual disputes or claims) arising out of or in connection with it or its subject matter or formation shall be governed by and construed in accordance with the law of England and Wales. Any dispute, claim or controversy relating in any way to this Agreement, the Offerings, your use of the Offerings, or to any products or services licensed or distributed by us will be resolved by binding arbitration as provided in this clause. Prior to commencing any formal arbitration proceedings, parties shall first seek settlement of any claim by mediation in accordance with the LCIA Mediation Rules, which Rules are deemed to be incorporated by reference into this clause. If the dispute is not settled by mediation within 14 days of the commencement of the mediation, or such further period as the parties shall agree in writing, the dispute shall be referred to and finally resolved by arbitration under the LCIA Rules, which are deemed to be incorporated by reference into this clause. The language to be used in the mediation and in the arbitration shall be English. The seat or legal place of arbitration shall be London.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>If you are located in any territory that is not specifically enumerated in the two sections above,</span> you may elect any of them to apply to you, otherwise this Agreement and any Claim (including non-contractual disputes or claims) arising out of or in connection with it or its subject matter or formation shall be governed by and construed in accordance with the law of Ireland. Any Claim relating in any way to this Agreement, the Offerings, your use of the Offerings, or to any products or services licensed or distributed by us will be resolved by binding arbitration as provided in this clause. Prior to commencing any formal arbitration proceedings, parties shall first seek settlement of any claim by mediation in accordance with the LCIA Mediation Rules, which Rules are deemed to be incorporated by reference into this clause. If the dispute is not settled by mediation within 14 days of the commencement of the mediation, or such further period as the parties shall agree in writing, the Claim shall be referred to and finally resolved by arbitration under the LCIA Rules, which are deemed to be incorporated by reference into this clause. The language to be used in the mediation and in the arbitration shall be English. The seat or legal place of arbitration shall be Dublin, Ireland.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Class Action Waiver.</span> You and we agree that each may bring claims against the other only on an individual basis, and not as a plaintiff or class member in any purported class or representative proceeding. You and we expressly waive any right to file a class action or seek relief on a class basis. Unless both you and we agree, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative or class proceeding. The arbitrator may award injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. If a court decides that applicable law precludes enforcement of any of this paragraph’s limitations as to a particular claim for relief, then that claim (and only that claim) must be severed from the arbitration and may be brought in court. If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provision set forth above shall be deemed null and void in its entirety and the parties shall be deemed to have not agreed to arbitrate disputes.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>30-Day Right to Opt-Out.</span> You have the right to opt-out and not be bound by the arbitration and class action waiver provisions set forth above by sending written notice of your decision to opt-out to the email address <a href='mailto:support@cryptomore.io'>support@cryptomore.io</a> with subject line LEGAL OPT OUT. The notice must be sent within 30 days of your first use of the Offerings, otherwise you shall be bound to arbitrate disputes and will be deemed to have agreed to waive any right to pursue a class action in accordance with the terms of those paragraphs. If you opt-out of these provisions, we will also not be bound by them.</p>
      <h4 class='text-primary title title-1' id='Miscellaneous'>
        Miscellaneous
      </h4>
      <p>These terms and any policies or operating rules posted by us on the Site or with respect to the Site constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these terms shall not operate as a waiver of such right or provision. These terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these terms is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment, or agency relationship created between you and us as a result of these terms or use of the Site or Services. You agree that these terms will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these terms and the lack of signing by the parties hereto to execute these terms.</p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Valid address.</span> The contact telephone number and e-mail address you filled in when you registered your account on this website are regarded as your valid notification address. If the above information has changed, you should update it in a timely manner. If the contact information provided by you is not accurate, or the contact information after the change is not informed in a timely manner, make the relevant notice (including but not limited to the agreement changes, legal documents, etc.) can not be served or not served on time, by your own assume the possible legal consequences.</p>
      <p>We reserve the right to do the following at any time without notice: (a) Suspend or terminate all or part of the operation and access of this website for any reason. (b) Modify or vary all or part of this website and its applicable policies or terms; (c) Interrupt all or part of the operation and access of this website when regular or irregular maintenance, error correction or other changes are necessary.</p>
      <p>This web site may contain links to other independent third-party web sites. Such links are provided only for the convenience of visitors to this web site. We do not provide any warranty, express or implied, regarding the content, services, information, etc. of the linked sites, nor do we consider such links to be our recommendation or authorization of the linked sites. You are required to independently judge your interaction with the linked site, we do not assume any responsibility for this.</p>
      <p>The rules of the website shall be an integral part of this agreement and shall have the same legal effect as the body of the agreement.</p>
      <p>We reserve the right to provide services to the United States, Chinese Mainland, Sudan, Hong Kong, Crimea, Burundi, Central Africa, Congo, Cuba, Iraq, Iran, North Korea, Lebanon, Libya, Sudan, Somalia, South Sudan, Syria, Yemen and Zimbabwe. <span class='text-primary' :style='{fontWeight:600}'>Before using the service, you promise and guarantee that you are NOT from the above countries or regions.</span> We unilaterally reserve the right to restrict or remove services from a particular region. If we unilaterally believe that the user is a citizen or resident of the country or region listed above, we may freeze or terminate these accounts.</p>
      <h4 class='text-primary title title-1' id='Contact Us'>
        Contact Us
      </h4>
      <p>In order to resolve a complaint regarding the Site or Services or to receive further information regarding the use of the Site or for Services, please contact us at:</p>
      <p>Crypto More Email: <a href='mailto:support@cryptomore.io'>support@cryptomore.io</a></p>
      <p><span class='text-primary' :style='{fontWeight:600}'>Note: this agreement will take effect on the date of release, CRYPTO MORE LTD. has the final right to interpret this agreement. This Agreement will remain in effect unless CRYPTO MORE LTD. makes adjustments to this Agreement and issues a new User Registration Agreement in accordance with relevant laws and regulations and website operations.</span></p>
    </div>
  </div>
</template>

<script setup lang='ts'>
import { defineAsyncComponent, ref, watch, computed } from 'vue'
import { scroll } from 'quasar'

const { getScrollTarget, setVerticalScrollPosition } = scroll

const HeadBackground = defineAsyncComponent(() => import('src/components/common/HeadBackground.vue'))
const Title = defineAsyncComponent(() => import('src/components/common/Title1.vue'))
const TableOfContent = defineAsyncComponent(() => import('src/components/agreement/TableOfContent.vue'))

const selected = ref('User Account')
const entries = ref([
  'User Account',
  'Description of Our Services',
  'Updates, Amendments, Changes to Terms',
  'Fees and Payment',
  'Privacy',
  'Term and Termination',
  'Intellectual Property',
  'Representations and Warranties',
  'Disclaimer',
  'Indemnification',
  'Force Majeure',
  'Binding Arbitration and Class Action Waiver',
  'Miscellaneous',
  'Contact Us'
])

watch(selected, () => {
  const el = document.getElementById(selected.value)
  if (!el) {
    return
  }
  const target = getScrollTarget(el)
  const offset = el.offsetTop - el.scrollHeight
  const duration = 1000
  setVerticalScrollPosition(target, offset, duration)
})

const scrollDistance = ref(0)
const tableOfContentMarginTop = computed(() => {
  const fixedVal = 460
  if (scrollDistance.value <= fixedVal) {
    return
  }
  return (scrollDistance.value - fixedVal).toFixed(0) + 'px'
})

const bodyHeight = ref(0)

const onScroll = (ev: unknown) => {
  const _ev = ev as Record<string, unknown>
  if (!_ev.position) {
    return
  }
  const pos = _ev.position as Record<string, number>
  if (pos.top >= bodyHeight.value) {
    return
  }
  scrollDistance.value = Number(pos.top)
}

const onResize = (size: Record<string, number>) => {
  bodyHeight.value = size.height
}

</script>

<style lang='sass' scoped>
.left
  width: 278px
  @media (max-width: 1280px)
    display: none

.right
  margin-left: 40px
  font-size: 16px
  font-weight: 500
  line-height: 26px
  max-width: 950px
  color: rgba(0, 71, 55, 0.6) !important
  padding-bottom: 120px
  @media (max-width: 1280px)
    margin-left: 6px
    margin-right: 6px
    max-width: 100%
  .title
    font-weight: 700
    line-height: 32px
  .title-1
    font-size: 24px
  .title-2
    font-size: 16px
</style>
