apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cryptomore-webui-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: cryptomore-webui
    k8s.kuboard.cn/workload: cryptomore-webui
    kubernetes.io/ingress.class: "devops-vpn-nginx-internal"
    nginx.com/sticky-cookie-services: "serviceName=kuboard srv_id expires=1h path=/"

spec:
  tls:
    - hosts:
        - '*.cryptomore.io'
        - cryptomore.io
      secretName: cryptomore-io-tls
  rules:
    - host: cryptomore.io
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: cryptomore-webui
              servicePort: 80
    - host: www.cryptomore.io
      http: *http_rules
    - host: cryptomore.xpool.top
      http: *http_rules
    - host: cryptomore.npool.top
      http: *http_rules
    - host: testnet.cryptomore.io
      http: *http_rules
